wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.20
    start_time: 1738743337
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      4: 3.8.20
      5: 0.12.21
      8:
      - 5
checkpoint:
  desc: null
  value: null
compute_device_id:
  desc: null
  value: 0
experiment_name:
  desc: null
  value: null
flex:
  desc: null
  value: false
graphics_device_id:
  desc: null
  value: 0
headless:
  desc: null
  value: false
horovod:
  desc: null
  value: false
load_run:
  desc: null
  value: null
max_iterations:
  desc: null
  value: null
num_envs:
  desc: null
  value: null
num_threads:
  desc: null
  value: 0
physics_engine:
  desc: null
  value: SimType.SIM_PHYSX
physx:
  desc: null
  value: false
pipeline:
  desc: null
  value: gpu
resume:
  desc: null
  value: false
rl_device:
  desc: null
  value: cuda:0
run_name:
  desc: null
  value: null
seed:
  desc: null
  value: null
sim_device:
  desc: null
  value: cuda:0
sim_device_id:
  desc: null
  value: 0
sim_device_type:
  desc: null
  value: cuda
slices:
  desc: null
  value: 0
subscenes:
  desc: null
  value: 0
task:
  desc: null
  value: anymal_c_rough
use_gpu:
  desc: null
  value: true
use_gpu_pipeline:
  desc: null
  value: true
